/* Generated by Yosys 0.56+30 (git sha1 2d90e80b5, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module my_ckt(clk, clk_g, rst_n, d, q1);
  input clk;
  wire clk;
  input clk_g;
  wire clk_g;
  input rst_n;
  wire rst_n;
  input d;
  wire d;
  output q1;
  wire q1;
  wire _0_;
  wire _1_;
  wire _2_;
  wire buf_out;
  wire q;

  // INV_X1 _6_ (
  //   .A(clk),
  //   .ZN(_0_)
  // );
  DFFR_X1 _2_ (
    .CK(clk_g),
    .D(buf_out),
    .Q(q1),
    .QN(_2_),
    .RN(rst_n)
  );
  DFFR_X1 _3_ (
    .CK(clk),
    .D(d),
    .Q(q),
    .QN(_1_),
    .RN(rst_n)
  );
  
  BUF_X8 _4_ (
    .A(q),
    .Z(buf_out)
  );

endmodule
