/* Generated by Yosys 0.56+30 (git sha1 2d90e80b5, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module my_ckt(clk, rst_n, d, b, f, g, q1);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input d;
  wire d;
  input b;
  wire b;
  input f;
  wire f;
  input g;
  wire g;
  output q1;
  wire q1;
  wire _0_;
  wire _1_;
  wire _2_;
  wire e;
  wire q;
  NOR2_X1 _3_ (
    .A1(q),
    .A2(g),
    .ZN(_0_)
  );
  XNOR2_X1 _4_ (
    .A(f),
    .B(_0_),
    .ZN(e)
  );
  DFFR_X1 _5_ (
    .CK(clk),
    .D(e),
    .Q(q1),
    .QN(_2_),
    .RN(rst_n)
  );
  DFFR_X1 _6_ (
    .CK(clk),
    .D(d),
    .Q(q),
    .QN(_1_),
    .RN(rst_n)
  );
endmodule
