/* Generated by Yosys 0.56+30 (git sha1 2d90e80b5, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module my_ckt(clk,rst_n, d, q1, out1);
  input clk;
  wire clk;
  wire clk_out;
  wire clk_out1;
  input rst_n;
  wire rst_n;
  input d;
  wire d;
  output q1;
  output out1;
  wire out1;
  wire q1;
  wire _0_;
  wire _1_;
  wire buf_out;
  wire q;

  BUF_X8 _7_ (
    .A(clk),
    .Z(clk_out)
  );

  BUF_X8 _8_ (
    .A(clk_out),
    .Z(clk_out1)
  );

  BUF_X8 _9_ (
    .A(clk_out1),
    .Z(clk_out2)
  );

  BUF_X8 _10_ (
    .A(clk_out2),
    .Z(clk_out3)
  );


  DFFR_X1 _2_ (
    .CK(clk_out3),
    .D(buf_out),
    .Q(q1),
    .QN(_1_),
    .RN(rst_n)
  );

  DFFR_X1 _3_ (
    .CK(clk_out1),
    .D(d),
    .Q(q),
    .QN(_0_),
    .RN(rst_n)
  );

  BUF_X8 _4_ (
    .A(q),
    .Z(buf_out)
  );


endmodule
